### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by subnetmarco** [Kong/unirest-java#15]
Create an Android version of Unirest-Java.

**Comment by 1762588562** [comment]
I used the demo  and  geted the  erro,How can i solve the  problem?
java.lang.ExceptionInInitializerError
                                                                                at com.mashape.unirest.http.HttpClientHelper.prepareRequest(HttpClientHelper.java:151)
                                                                                at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:131)
                                                                                at com.mashape.unirest.request.BaseRequest.asJson(BaseRequest.java:68)
