### ISSUE TITLE
Improved error handling

### ISSUE THREAD

**Issue by ghost** [Kong/unirest-java#194]
Sample code:
```
    public static void main(String[] args) throws Exception {
        HttpResponse<JsonNode> response = Unirest.get("http://ajaygautam.com/random.json").asJson();
        System.out.println("Status: " + response.getStatusText());
    }
```

Fails at asJson() with:
```
/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/...

Exception in thread "main" com.mashape.unirest.http.exceptions.UnirestException: java.lang.RuntimeException: java.lang.RuntimeException: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:143)
	at com.mashape.unirest.request.BaseRequest.asJson(BaseRequest.java:68)
	at ScrapUnirestSample.main(ScrapUnirestSample.java:7)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
	at com.mashape.unirest.http.HttpResponse.<init>(HttpResponse.java:106)
	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:139)
	... 7 more
Caused by: java.lang.RuntimeException: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
	at com.mashape.unirest.http.JsonNode.<init>(JsonNode.java:51)
	at com.mashape.unirest.http.HttpResponse.<init>(HttpResponse.java:95)
	... 8 more
Caused by: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:433)
	at org.json.JSONArray.<init>(JSONArray.java:106)
	at org.json.JSONArray.<init>(JSONArray.java:145)
	at com.mashape.unirest.http.JsonNode.<init>(JsonNode.java:48)
	... 9 more

```

**Expected**: An error detailing whats actually going on (eg: unable to get resource from URI)

More info: asString() is better behaved!

**Comment by Catscratch** [comment]
+1

Also, it would be helpful to put the raw body into the UnirestException (e.g. ex.getRawBody). 
When json parsing fails, I need more information what the body was. But when the UnirestException is catched, the body is already gone.

**Comment by ryber** [comment]
Hello, I've resolved this on the OpenUnirest fork https://github.com/OpenUnirest/unirest-java/blob/master/src/test/java/io/github/openunirest/http/UnirestTest.java#L726-L735

available in the current published version in Maven

**Comment by ryber** [comment]
Hello, this should be resolved or addressed in Unirest 2. Please see the [upgrade guide](https://github.com/Kong/unirest-java/blob/master/UPGRADE_GUIDE.md) for important changes.
