### ISSUE TITLE
No field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier

### ISSUE THREAD

**Issue by celiken** [Kong/unirest-java#223]
I am using Unirest 1.4.9.
 When I make my first call to the API, I get this error :
`Caused by: java.lang.NoSuchFieldError: No field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar:classes2.dex)`

Did somebody already had this issue?
And do you have any idea to fix it?

I've already try checking around the gradle dependencies, but it doesn't look like there is conflicts... :/

**Comment by SureshMaidaragi** [comment]
yes It oo had the same issue w

**Comment by SureshMaidaragi** [comment]
12-19 17:06:02.132 29094-29094/com.example.sureshmaidaragi.amazonrekognition E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                               Process: com.example.sureshmaidaragi.amazonrekognition, PID: 29094
                                                                                               java.lang.NoSuchFieldError: No field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar:classes2.dex)
                                                                                                   at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:144)
                                                                                                   at com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory.getPreferredSocketFactory(ApacheConnectionManagerFactory.java:88)
                                                                                                   at com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory.create(ApacheConnectionManagerFactory.java:65)
                                                                                                   at com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory.create(ApacheConnectionManagerFactory.java:58)
                                                                                                   at com.amazonaws.http.apache.client.impl.ApacheHttpClientFactory.create(ApacheHttpClientFactory.java:50)
                                                                                                   at com.amazonaws.http.apache.client.impl.ApacheHttpClientFactory.create(ApacheHttpClientFactory.java:38)
                                                                                                   at com.amazonaws.http.AmazonHttpClient.<init>(AmazonHttpClient.java:315)
                                                                                                   at com.amazonaws.http.AmazonHttpClient.<init>(AmazonHttpClient.java:299)
                                                                                                   at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:172)
                                                                                                   at com.amazonaws.services.rekognition.AmazonRekognitionClient.<init>(AmazonRekognitionClient.java:288)
                                                                                                   at com.amazonaws.services.rekognition.AmazonRekognitionClientBuilder.build(AmazonRekognitionClientBuilder.java:60)
                                                                                                   at com.amazonaws.services.rekognition.AmazonRekognitionClientBuilder.build(AmazonRekognitionClientBuilder.java:26)
                                                                                                   at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
                                                                                                   at com.example.sureshmaidaragi.amazonrekognition.MainActivity.uploadForAmazonRek(MainActivity.java:596)
                                                                                                   at com.example.sureshmaidaragi.amazonrekognition.MainActivity.onActivityResult(MainActivity.java:216)
                                                                                                   at android.app.Activity.dispatchActivityResult(Activity.java:6946)
                                                                                                   at android.app.ActivityThread.deliverResults(ActivityThread.java:4126)
                                                                                                   at android.app.ActivityThread.handleSendResult(ActivityThread.java:4173)
                                                                                                   at android.app.ActivityThread.-wrap20(ActivityThread.java)
                                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1546)
                                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                                                   at android.app.ActivityThread.main(ActivityThread.java:6165)
                                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
                                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
12-19 17:06:08.181 29094-29103/com.example.sureshmaidaragi.amazonrekognition E/System: Uncaught exception thrown by finalizer
12-19 17:06:08.181 29094-29103/com.example.sureshmaidaragi.amazonrekognition E/System: java.lang.NullPointerException: Attempt to invoke interface method 'org.apache.http.conn.HttpClientConnectionManager com.amazonaws.http.apache.client.impl.ConnectionManagerAwareHttpClient.getHttpClientConnectionManager()' on a null object reference
                                                                                           at com.amazonaws.http.AmazonHttpClient.shutdown(AmazonHttpClient.java:425)
                                                                                           at com.amazonaws.http.AmazonHttpClient.finalize(AmazonHttpClient.java:412)
                                                                                           at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:222)
                                                                                           at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:209)
                                                                                           at java.lang.Thread.run(Thread.java:761)

**Comment by u2tall** [comment]
I'm having the same issue. 
Has anyone found a solution to this?

**Comment by ryber** [comment]
You most likely have a different version of Apache HttpClient on your classpath that is getting picked up before the one Unirest expects. We will have a new version of Unirest out shortly that has a updated Apache Client but that may not fix your issue. Take a look at mvn dependency:tree (or similar if not using maven) to see where you may have conflicts

**Comment by saachipahwa** [comment]
I have this same error - I've found that lintClassPath uses a different version of Apache HttpClient than Unirest version 3.13.11 but I'm not sure how to fix this?

**Comment by SvintXprecious** [comment]
> 

Were you able to find the solution?

**Comment by SvintXprecious** [comment]
> I too had the same issue while running amazon rekognition sample code, finding solution from two days, no positive yet
> 
> 12-19 17:06:02.132 29094-29094/com.example.sureshmaidaragi.amazonrekognition E/AndroidRuntime: FATAL EXCEPTION: main Process: com.example.sureshmaidaragi.amazonrekognition, PID: 29094 java.lang.NoSuchFieldError: No field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar:classes2.dex) at org.apache.http.conn.ssl.SSLConnectionSocketFactory.(SSLConnectionSocketFactory.java:144) at com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory.getPreferredSocketFactory(ApacheConnectionManagerFactory.java:88) at com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory.create(ApacheConnectionManagerFactory.java:65) at com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory.create(ApacheConnectionManagerFactory.java:58) at com.amazonaws.http.apache.client.impl.ApacheHttpClientFactory.create(ApacheHttpClientFactory.java:50) at com.amazonaws.http.apache.client.impl.ApacheHttpClientFactory.create(ApacheHttpClientFactory.java:38) at com.amazonaws.http.AmazonHttpClient.(AmazonHttpClient.java:315) at com.amazonaws.http.AmazonHttpClient.(AmazonHttpClient.java:299) at com.amazonaws.AmazonWebServiceClient.(AmazonWebServiceClient.java:172) at com.amazonaws.services.rekognition.AmazonRekognitionClient.(AmazonRekognitionClient.java:288) at com.amazonaws.services.rekognition.AmazonRekognitionClientBuilder.build(AmazonRekognitionClientBuilder.java:60) at com.amazonaws.services.rekognition.AmazonRekognitionClientBuilder.build(AmazonRekognitionClientBuilder.java:26) at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46) at com.example.sureshmaidaragi.amazonrekognition.MainActivity.uploadForAmazonRek(MainActivity.java:596) at com.example.sureshmaidaragi.amazonrekognition.MainActivity.onActivityResult(MainActivity.java:216) at android.app.Activity.dispatchActivityResult(Activity.java:6946) at android.app.ActivityThread.deliverResults(ActivityThread.java:4126) at android.app.ActivityThread.handleSendResult(ActivityThread.java:4173) at android.app.ActivityThread.-wrap20(ActivityThread.java) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1546) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:154) at android.app.ActivityThread.main(ActivityThread.java:6165) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778) 12-19 17:06:08.181 29094-29103/com.example.sureshmaidaragi.amazonrekognition E/System: Uncaught exception thrown by finalizer 12-19 17:06:08.181 29094-29103/com.example.sureshmaidaragi.amazonrekognition E/System: java.lang.NullPointerException: Attempt to invoke interface method 'org.apache.http.conn.HttpClientConnectionManager com.amazonaws.http.apache.client.impl.ConnectionManagerAwareHttpClient.getHttpClientConnectionManager()' on a null object reference at com.amazonaws.http.AmazonHttpClient.shutdown(AmazonHttpClient.java:425) at com.amazonaws.http.AmazonHttpClient.finalize(AmazonHttpClient.java:412) at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:222) at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:209) at java.lang.Thread.run(Thread.java:761)

Were you able to find the solution to this?
