### ISSUE TITLE
App in Android studio is crashing, and I'm receiving this error messages in LogCat

### ISSUE THREAD

**Issue by jonesgreg** [Kong/unirest-java#224]
java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                                at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                                                at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                                at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                                at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                at java.lang.Thread.run(Thread.java:818)
                                                                             Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/client/config/RequestConfig;
                                                                                at com.mashape.unirest.http.options.Options.refresh(Options.java:70)
                                                                                at com.mashape.unirest.http.options.Options.<clinit>(Options.java:46)
                                                                                at com.mashape.unirest.http.HttpClientHelper.prepareRequest(HttpClientHelper.java:151)
                                                                                at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:131)
                                                                                at com.mashape.unirest.request.BaseRequest.asJson(BaseRequest.java:68)
                                                                                at com.example.gregoryjones.api.JSONQuery.doInBackground(JSONQuery.java:73)
                                                                                at com.example.gregoryjones.api.JSONQuery.doInBackground(JSONQuery.java:20)
                                                                                at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                                at java.lang.Thread.run(Thread.java:818) 
                                                                             Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.client.config.RequestConfig" on path: DexPathList[[zip file "/data/app/com.example.gregoryjones.api-2/base.apk"],nativeLibraryDirectories=[/data/app/com.example.gregoryjones.api-2/lib/x86, /vendor/lib, /system/lib]]
                                                                                at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                                at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                                at com.mashape.unirest.http.options.Options.refresh(Options.java:70) 
                                                                                at com.mashape.unirest.http.options.Options.<clinit>(Options.java:46) 
                                                                                at com.mashape.unirest.http.HttpClientHelper.prepareRequest(HttpClientHelper.java:151) 
                                                                                at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:131) 
                                                                                at com.mashape.unirest.request.BaseRequest.asJson(BaseRequest.java:68) 
                                                                                at com.example.gregoryjones.api.JSONQuery.doInBackground(JSONQuery.java:73) 
                                                                                at com.example.gregoryjones.api.JSONQuery.doInBackground(JSONQuery.java:20) 
                                                                                at android.os.AsyncTask$2.call(AsyncTask.java:295) 
                                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                                at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                                at java.lang.Thread.run(Thread.java:818) 
                                                                            	Suppressed: java.lang.ClassNotFoundException: org.apache.http.client.config.RequestConfig
                                                                                at java.lang.Class.classForName(Native Method)
                                                                                at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                                at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                                at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                                		... 14 more

**Comment by cnix3297** [comment]
sorry to necromancy but did you find a solution for  this?

**Comment by ryber** [comment]
You most likely have a different version of Apache HttpClient on your classpath that is getting picked up before the one Unirest expects. We will have a new version of Unirest out shortly that has a updated Apache Client but that may not fix your issue. Take a look at mvn dependency:tree (or similar if not using maven) to see where you may have conflicts

**Comment by cnix3297** [comment]
I got figured it out... it was a mix of like 6 or 7 problems that blended
to be a recipe for disaster. Thank you for taking the time to email me
back. I should have posted up that it was resolved.
