### ISSUE TITLE
java.lang.NoClassDefFoundError: com/mashape/unirest/http/async/Callback

### ISSUE THREAD

**Issue by neilyoung** [Kong/unirest-java#229]
I'm having a weird issue with the release build of my app. Everything works fine as long as it runs in the debugger. After having finally build the JAR this exceptions appears:

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/mashape/unirest/http/async/Callback
...
Caused by: java.lang.ClassNotFoundException: com.mashape.unirest.http.async.Callback
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

```

The classpath contains these items:

unirest-java-1.4.9.jar
httpclient-4.5.2.jar
httpasyncclient-4.1.1.jar

The call is like so:

```
       Future<HttpResponse<String>> futureHttpResponse = Unirest.post(url)
                .header("Accept", "application/json")
                .basicAuth(username, password)
                .body(body)
                .asStringAsync(new Callback<String>() {
                    @Override
                    public void completed(HttpResponse<String> httpResponse) {
                    }

                    @Override
                    public void failed(UnirestException e) {
                    }

                    @Override
                    public void cancelled() {
                    }
                });

```

As said: It runs in debugger, but not as a JAR.. Very strange... As far as I can see, all required dependencies are resolved and the unirest JAR contains a Callback class. Any idea?

**Comment by neilyoung** [comment]
My bad, sorry

**Comment by cordoval** [comment]
what was it??? i ran into the same issue

**Comment by cordoval** [comment]
nvm you forgot to move under /share/java the jar for the unirest ha ha lol
