### ISSUE TITLE
No buffer space available (maximum connections reached?): connect

### ISSUE THREAD

**Issue by faisalbasra** [Kong/unirest-java#238]
I am facing the following exception after some days continuously. 

java.lang.RuntimeException: org.apache.http.nio.reactor.IOReactorException: Failure opening selector
	at com.mashape.unirest.http.options.Options.refresh(Options.java:90) ~[unirest-java-1.4.9.jar:?]
	at com.mashape.unirest.http.Unirest.setTimeouts(Unirest.java:94) ~[unirest-java-1.4.9.jar:?]
	at com.sas.teradaa.das.TeradataDatabaseAPI.getNBOByMacro(TeradataDatabaseAPI.java:179) ~[classes/:?]
	at com.sas.teradaa.das.TeradataDatabaseAPI.getNextBestOffersByMacro(TeradataDatabaseAPI.java:72) [classes/:?]
	at com.sas.teradaa.das.ws.TeradataDatabaseAPIDelegate.getNextBestOffersByMacro(TeradataDatabaseAPIDelegate.java:48) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor53.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_162]
	at com.sun.xml.ws.api.server.InstanceResolver$1.invoke(InstanceResolver.java:246) [webservices-rt-1.1.jar:1.0]
	at com.sun.xml.ws.server.InvokerTube$2.invoke(InvokerTube.java:146) [webservices-rt-1.1.jar:1.0]
	at com.sun.xml.ws.server.sei.EndpointMethodHandler.invoke(EndpointMethodHandler.java:257) [webservices-rt-1.1.jar:1.0]
	at com.sun.xml.ws.server.sei.SEIInvokerTube.processRequest(SEIInvokerTube.java:93) [webservices-rt-1.1.jar:1.0]
	at com.sun.xml.ws.api.pipe.Fiber.__doRun(Fiber.java:595) [webservices-rt-1.1.jar:1.0]
	at com.sun.xml.ws.api.pipe.Fiber._doRun(Fiber.java:554) [webservices-rt-1.1.jar:1.0]
	at com.sun.xml.ws.api.pipe.Fiber.doRun(Fiber.java:539) [webservices-rt-1.1.jar:1.0]
	at com.sun.xml.ws.api.pipe.Fiber.runSync(Fiber.java:436) [webservices-rt-1.1.jar:1.0]
	at com.sun.xml.ws.server.WSEndpointImpl$2.process(WSEndpointImpl.java:243) [webservices-rt-1.1.jar:1.0]
	at com.sun.xml.ws.transport.http.HttpAdapter$HttpToolkit.handle(HttpAdapter.java:444) [webservices-rt-1.1.jar:1.0]
	at com.sun.xml.ws.transport.http.HttpAdapter.handle(HttpAdapter.java:244) [webservices-rt-1.1.jar:1.0]
	at com.sun.xml.ws.transport.http.servlet.ServletAdapter.handle(ServletAdapter.java:135) [webservices-rt-1.1.jar:1.0]
	at com.sun.xml.ws.transport.http.servlet.WSServletDelegate.doGet(WSServletDelegate.java:129) [webservices-rt-1.1.jar:1.0]
	at com.sun.xml.ws.transport.http.servlet.WSServletDelegate.doPost(WSServletDelegate.java:160) [webservices-rt-1.1.jar:1.0]
	at com.sun.xml.ws.transport.http.servlet.WSServlet.doPost(WSServlet.java:75) [webservices-rt-1.1.jar:1.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) [servlet-api.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:9.0.6]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.6]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-websocket.jar:9.0.6]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.6]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.6]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) [catalina.jar:9.0.6]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:9.0.6]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:494) [catalina.jar:9.0.6]
	at org.apache.catalina.valves.RequestFilterValve.process(RequestFilterValve.java:348) [catalina.jar:9.0.6]
	at org.apache.catalina.valves.RemoteAddrValve.invoke(RemoteAddrValve.java:52) [catalina.jar:9.0.6]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137) [catalina.jar:9.0.6]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.6]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:651) [catalina.jar:9.0.6]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [catalina.jar:9.0.6]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.6]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:407) [tomcat-coyote.jar:9.0.6]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-coyote.jar:9.0.6]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:754) [tomcat-coyote.jar:9.0.6]
	at org.apache.tomcat.util.net.Nio2Endpoint$SocketProcessor.doRun(Nio2Endpoint.java:1710) [tomcat-coyote.jar:9.0.6]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.6]
	at org.apache.tomcat.util.net.AbstractEndpoint.processSocket(AbstractEndpoint.java:1007) [tomcat-coyote.jar:9.0.6]
	at org.apache.tomcat.util.net.Nio2Endpoint$Nio2SocketWrapper$4.completed(Nio2Endpoint.java:540) [tomcat-coyote.jar:9.0.6]
	at org.apache.tomcat.util.net.Nio2Endpoint$Nio2SocketWrapper$4.completed(Nio2Endpoint.java:518) [tomcat-coyote.jar:9.0.6]
	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:126) [?:1.8.0_162]
	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:281) [?:1.8.0_162]
	at sun.nio.ch.WindowsAsynchronousSocketChannelImpl$ReadTask.completed(WindowsAsynchronousSocketChannelImpl.java:579) [?:1.8.0_162]
	at sun.nio.ch.Iocp$EventHandlerTask.run(Iocp.java:397) [?:1.8.0_162]
	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: org.apache.http.nio.reactor.IOReactorException: Failure opening selector
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.<init>(AbstractMultiworkerIOReactor.java:144) ~[httpcore-nio-4.3.2.jar:4.3.2]
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.<init>(DefaultConnectingIOReactor.java:81) ~[httpcore-nio-4.3.2.jar:4.3.2]
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.<init>(DefaultConnectingIOReactor.java:107) ~[httpcore-nio-4.3.2.jar:4.3.2]
	at com.mashape.unirest.http.options.Options.refresh(Options.java:85) ~[unirest-java-1.4.9.jar:?]
	... 55 more
Caused by: java.io.IOException: Unable to establish loopback connection
	at sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:94) ~[?:1.8.0_162]
	at sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:61) ~[?:1.8.0_162]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_162]
	at sun.nio.ch.PipeImpl.<init>(PipeImpl.java:171) ~[?:1.8.0_162]
	at sun.nio.ch.SelectorProviderImpl.openPipe(SelectorProviderImpl.java:50) ~[?:1.8.0_162]
	at java.nio.channels.Pipe.open(Pipe.java:155) ~[?:1.8.0_162]
	at sun.nio.ch.WindowsSelectorImpl.<init>(WindowsSelectorImpl.java:127) ~[?:1.8.0_162]
	at sun.nio.ch.WindowsSelectorProvider.openSelector(WindowsSelectorProvider.java:44) ~[?:1.8.0_162]
	at java.nio.channels.Selector.open(Selector.java:227) ~[?:1.8.0_162]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.<init>(AbstractMultiworkerIOReactor.java:142) ~[httpcore-nio-4.3.2.jar:4.3.2]
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.<init>(DefaultConnectingIOReactor.java:81) ~[httpcore-nio-4.3.2.jar:4.3.2]
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.<init>(DefaultConnectingIOReactor.java:107) ~[httpcore-nio-4.3.2.jar:4.3.2]
	at com.mashape.unirest.http.options.Options.refresh(Options.java:85) ~[unirest-java-1.4.9.jar:?]
	... 55 more
Caused by: java.net.SocketException: No buffer space available (maximum connections reached?): connect
	at sun.nio.ch.Net.connect0(Native Method) ~[?:1.8.0_162]
	at sun.nio.ch.Net.connect(Net.java:454) ~[?:1.8.0_162]
	at sun.nio.ch.Net.connect(Net.java:446) ~[?:1.8.0_162]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[?:1.8.0_162]
	at java.nio.channels.SocketChannel.open(SocketChannel.java:189) ~[?:1.8.0_162]
	at sun.nio.ch.PipeImpl$Initializer$LoopbackConnector.run(PipeImpl.java:127) ~[?:1.8.0_162]
	at sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:76) ~[?:1.8.0_162]
	at sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:61) ~[?:1.8.0_162]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_162]
	at sun.nio.ch.PipeImpl.<init>(PipeImpl.java:171) ~[?:1.8.0_162]
	at sun.nio.ch.SelectorProviderImpl.openPipe(SelectorProviderImpl.java:50) ~[?:1.8.0_162]
	at java.nio.channels.Pipe.open(Pipe.java:155) ~[?:1.8.0_162]
	at sun.nio.ch.WindowsSelectorImpl.<init>(WindowsSelectorImpl.java:127) ~[?:1.8.0_162]
	at sun.nio.ch.WindowsSelectorProvider.openSelector(WindowsSelectorProvider.java:44) ~[?:1.8.0_162]
	at java.nio.channels.Selector.open(Selector.java:227) ~[?:1.8.0_162]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.<init>(AbstractMultiworkerIOReactor.java:142) ~[httpcore-nio-4.3.2.jar:4.3.2]
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.<init>(DefaultConnectingIOReactor.java:81) ~[httpcore-nio-4.3.2.jar:4.3.2]
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.<init>(DefaultConnectingIOReactor.java:107) ~[httpcore-nio-4.3.2.jar:4.3.2]
	at com.mashape.unirest.http.options.Options.refresh(Options.java:85) ~[unirest-java-1.4.9.jar:?]
	... 55 more

**Comment by ryber** [comment]
this is most likely fixed in the new version coming out

**Comment by ryber** [comment]
Hello, this should be resolved or addressed in Unirest 2. Please see the [upgrade guide](https://github.com/Kong/unirest-java/blob/master/UPGRADE_GUIDE.md) for important changes.
