### ISSUE TITLE
Constructor ref error with Amazon corretto jdk1.8.0_202

### ISSUE THREAD

**Issue by ryber** [Kong/unirest-java#270]
**Describe the bug**
java.lang.BootstrapMethodError: java.lang.IllegalAccessError: no such constructor: kong.unirest.apache.ApacheAsyncClient.<init>(Config)void/newInvokeSpecial
   at kong.unirest.Config.<init>(Config.java:69)
   at kong.unirest.Unirest.<clinit>(Unirest.java:30)

**To Reproduce**
Fire up Unirest under corretto

**Environmental Data:**
 - corretto jdk1.8.0_202

**Comment by ryber** [comment]
This is actually because the person who reported it had a older version of Apache http client in maven before Unirest and this was the final error:
```
caused by: java.lang.NoClassDefFoundError: org/apache/http/concurrent/FutureCallback
    at java.lang.invoke.MethodHandleNatives.resolve(Native Method)
```

It's weird that this even throws when the constructor is never invoked. We should also throw a better error which explains the problem and solution. Apache Http Client is used by lots of things and being on a old crusty version is a constant issue

**Comment by ryber** [comment]
make a better explanation for errors that happen when the user has a older version of Apache on the path https://github.com/Kong/unirest-java/commit/20ec053431f891e57152441565fef30b8505ae47
