### ISSUE TITLE
Configure object mappers per request

### ISSUE THREAD

**Issue by teamlead-agbaje** [Kong/unirest-java#292]
Hi,

According to the documentation, "Object Mappers can be configured globally, per config, or on a per-request basis."

I'm trying to achieve a "per request" configuration. I tried this:

```
HttpResponse<ResponseSignUp> response = Unirest.post(signUpUrl)
                    .withObjectMapper(new JacksonObjectMapper())
                    .header("content-type", "application/json")
                    .header("Accept", "*/*")
                    .body(params)
                    .asObject(ResponseSignUp.class);
```

But all I keep getting is an exception telling me to use the global configuration:

`kong.unirest.UnirestException: No Object Mapper Configured. Please config one with Unirest.config().setObjectMapper
`
Please, what am I missing?

Cheers!

**Comment by ryber** [comment]
Apparently It's working on the response mapping but not on the body mapping. I've fix this and . I'm running a release now. It should take about 20-30 minutes for it to make it into mvn central . (2.3.17)

**Comment by teamlead-agbaje** [comment]
Oh, alright @ryber. Thanks, I'll wait.

**Comment by ryber** [comment]
2.3.17 is ready

**Comment by teamlead-agbaje** [comment]
Hi @ryber,

I tested the 2.3.17 and I'm now getting a different error:

```
ERROR | 2019-09-05 12:17:32 | [scheduling-1] support.TaskUtils$LoggingErrorHandler (TaskUtils.java:96) - Unexpected error occurred in scheduled task.
java.lang.StackOverflowError: null
	at com.google.gson.internal.$Gson$Types.canonicalize($Gson$Types.java:106) ~[gson-2.8.5.jar!/:?]
	at com.google.gson.reflect.TypeToken.<init>(TypeToken.java:72) ~[gson-2.8.5.jar!/:?]
	at com.google.gson.reflect.TypeToken.get(TypeToken.java:296) ~[gson-2.8.5.jar!/:?]
```

so basically, for whatever reason, when I try making an API call (which I posted above), something breaks that's connected to gson. I'm not even using gson. I'm using JacksonObjectMapper.

Thanks

**Comment by ryber** [comment]
Can you give more of a stack trace for where this intersects with Unirest?

**Comment by ryber** [comment]
As you can see from the dependency tree Gson is not part of Unirest's non-test depenencies:

```
[INFO] ----------------------< com.konghq:unirest-java >-----------------------
[INFO] Building unirest-java 2.3.18-SNAPSHOT                              [2/4]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ unirest-java ---
[INFO] com.konghq:unirest-java:jar:2.3.18-SNAPSHOT
[INFO] +- org.apache.httpcomponents:httpclient:jar:4.5.9:compile
[INFO] |  +- org.apache.httpcomponents:httpcore:jar:4.4.11:compile
[INFO] |  +- commons-logging:commons-logging:jar:1.2:compile
[INFO] |  \- commons-codec:commons-codec:jar:1.11:compile
[INFO] +- org.apache.httpcomponents:httpmime:jar:4.5.9:compile
[INFO] +- org.apache.httpcomponents:httpasyncclient:jar:4.1.4:compile
[INFO] |  \- org.apache.httpcomponents:httpcore-nio:jar:4.4.10:compile
[INFO] \- org.json:json:jar:20180813:compile
[INFO] 
[INFO] 
[INFO] --------------< com.konghq:unirest-objectmapper-jackson >---------------
[INFO] Building unirest-objectmapper-jackson 2.3.18-SNAPSHOT              [4/4]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ unirest-objectmapper-jackson ---
[INFO] com.konghq:unirest-objectmapper-jackson:jar:2.3.18-SNAPSHOT
[INFO] +- com.konghq:unirest-java:jar:2.3.18-SNAPSHOT:provided
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.5.9:provided
[INFO] |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.11:provided
[INFO] |  |  +- commons-logging:commons-logging:jar:1.2:provided
[INFO] |  |  \- commons-codec:commons-codec:jar:1.11:provided
[INFO] |  +- org.apache.httpcomponents:httpmime:jar:4.5.9:provided
[INFO] |  +- org.apache.httpcomponents:httpasyncclient:jar:4.1.4:provided
[INFO] |  |  \- org.apache.httpcomponents:httpcore-nio:jar:4.4.10:provided
[INFO] |  \- org.json:json:jar:20180813:provided
[INFO] \- com.fasterxml.jackson.core:jackson-databind:jar:2.9.9.3:compile
[INFO]    +- com.fasterxml.jackson.core:jackson-annotations:jar:2.9.0:compile
[INFO]    \- com.fasterxml.jackson.core:jackson-core:jar:2.9.9:compile
[INFO] ------------------------------------------------------------------------
```

Could it be that this error is the body you are getting back from the remote? Perhaps because your body is not properly formatted?

The JacksonMapper is a bare bones simple Jackson configuration if you need the more advanced data-binding features of Jackson you can inject your own Jackson-ObjectMapper into the unirest JacksonObjectMapper

**Comment by teamlead-agbaje** [comment]
Hi @ryber,

Many apologies! The issue is not with the  unirest. I found a rogue gson lurking somewhere.

Everything works well. Thanks for the fix!
