### ISSUE TITLE
trying to download image using thenConsume gives org.apache.http.ConnectionClosedException

### ISSUE THREAD

**Issue by mukundcs1611** [Kong/unirest-java#293]
I haven't used Consumer interface in Java 8 . I was trying to download the image using unirest.get().thenConsume() but when I do it it gives me the following exception:

**org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body **

There are no examples mentioned anywhere on the internet explaining how to properly use thenConsume(). Can I get some information on the usage. 

**Additional context**
The snippet of the code:
```
  public InputStream downloadFile(String fileUrl, String token) {
        AtomicReference<InputStream> f = new AtomicReference<>();


        Unirest.get(fileUrl).thenConsume(rawResponse -> {
            try {
                BufferedImage image = ImageIO.read(rawResponse.getContent());
                ImageIO.write(image, "jpeg", new File("temp_images/1.jpeg"));
            } catch (IOException e) {
                e.printStackTrace();
            }
        });
        
        return f.get();
    }
```

The Exception that I see: 

```
org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 593,118; received: 7,391)
	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:178)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
	at java.desktop/javax.imageio.stream.FileCacheImageInputStream.readUntil(FileCacheImageInputStream.java:145)
	at java.desktop/javax.imageio.stream.FileCacheImageInputStream.read(FileCacheImageInputStream.java:190)
	at java.desktop/com.sun.imageio.plugins.jpeg.JPEGImageReader.readInputData(JPEGImageReader.java:312)
	at java.desktop/com.sun.imageio.plugins.jpeg.JPEGImageReader.readImage(Native Method)
	at java.desktop/com.sun.imageio.plugins.jpeg.JPEGImageReader.readInternal(JPEGImageReader.java:1311)
	at java.desktop/com.sun.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:1110)
	at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1468)
	at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1363)
```

**Comment by ryber** [comment]
I added a few tests to mimic this since I didn't have any covering using the consumers to write a file. You can find them here: https://github.com/Kong/unirest-java/blob/d69ed3439096202a6f3ee77605b0540c086de8db/unirest/src/test/java/BehaviorTests/ConsumerTest.java#L70-L107

Unfortunately for this issue they pass, which seems to indicate that at least the very basic functions of unirest are maybe not the problem. 

The error you are getting is typically a server side problem, the server told you that the content-length was 593,118, but in fact it was 7,391

this could also be caused if unirest closed the connection, while not part of the suite I also downloaded a much bigger file and it seemed to work (using https://upload.wikimedia.org/wikipedia/commons/6/6a/Mona_Lisa.jpg)

**Comment by mukundcs1611** [comment]
Indeed! I tried with the image file that @ryber has given it worked perfectly. It might have been a server-side issue thanks for the help @ryber !
