### ISSUE TITLE
Standalone complains of missing Ivy classes.

### ISSUE THREAD

**Issue by dailytabs** [Kong/unirest-java#425]
**Describe the bug**
Grabbing standalone. Running `groovy script.groovy` and getting error.

**To Reproduce**
```
@Grapes([
        @Grab('com.konghq:unirest-java:3.11.09:standalone')
])

def steps = get("https://api.tempo.io/core/3/accounts")
        .header('Authorization', 'Bearer ...')
        .asObject(List).body

System.out.println steps as String
```

**Expected behavior**
Standalone package to not require outside classes to function.

**Environmental Data:**
 - Java 17
 - Unirest 3.11.09
 - Groovy 3.0.9

**Additional context**
```
Caught: java.lang.NoClassDefFoundError: org/apache/ivy/util/MessageLogger
java.lang.NoClassDefFoundError: org/apache/ivy/util/MessageLogger
Caused by: java.lang.ClassNotFoundException: org.apache.ivy.util.MessageLogger
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
```

**Comment by dailytabs** [comment]
Same error whether I use standalone or not.

**Comment by ryber** [comment]
Unirest has no dependency on Ivy. At the minimum its:

```
[INFO] \- com.konghq:unirest-java:jar:standalone:3.11.09:compile
[INFO]    +- org.apache.httpcomponents:httpclient:jar:4.5.13:compile
[INFO]    |  +- org.apache.httpcomponents:httpcore:jar:4.4.13:compile
[INFO]    |  +- commons-logging:commons-logging:jar:1.2:compile
[INFO]    |  \- commons-codec:commons-codec:jar:1.11:compile
[INFO]    +- org.apache.httpcomponents:httpmime:jar:4.5.13:compile
[INFO]    +- org.apache.httpcomponents:httpcore-nio:jar:4.4.13:compile
[INFO]    +- org.apache.httpcomponents:httpasyncclient:jar:4.1.4:compile
[INFO]    \- com.google.code.gson:gson:jar:2.8.6:compile`
```

Can you get more of a stack trace to show where in Apache or Unirest it's trying to load that class?

**Comment by ryber** [comment]
@dailytabs Ivy is a dependency management library, There is no reason Unirest would use it, it is very likely used by Grape and that is where your error is coming from

**Comment by ryber** [comment]
Closing as this is most likely a issue with Grape

**Comment by dailytabs** [comment]
Sorry, I meant to come back and close this. It was Gradle getting in the way.
