### ISSUE TITLE
Didn't find class "java.net.http.HttpClient" on path: DexPathList

### ISSUE THREAD

**Issue by sunithapremjee** [Kong/unirest-java#449]
Exception:
     Caused by: java.lang.ClassNotFoundException: Didn't find class "java.net.http.HttpClient" on path: DexPathList[[zip file "/data/app/~~1LjDphNSxbAIcpr2OuHVhw==/com.camera_flash--Bh9JUsYTbEfigKV2J2xag==/base.apk"],nativeLibraryDirectories=[/data/app/~~1LjDphNSxbAIcpr2OuHVhw==.om.camera_flash--Bh9JUsYTbEfigKV2J2xag==/lib/arm64, /system/lib64, /system/system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at kong.unirest.core.java.JavaClientBuilder.apply(JavaClientBuilder.java:44) 
        at kong.unirest.core.java.JavaClient.<init>(JavaClient.java:49) 
        at kong.unirest.core.Config$$ExternalSyntheticLambda0.apply(Unknown Source:4) 
        at kong.unirest.core.Config.buildClient(Config.java:664) 
        at kong.unirest.core.Config.getClient(Config.java:649) 
        at kong.unirest.core.BaseRequest.request(BaseRequest.java:343) 
        at kong.unirest.core.BaseRequest.asJson(BaseRequest.java:228) 
        at com.camera_flash.UnirestHTTP.post_request(UnirestHTTP.java:79) 

Unirest Function call:-
		Unirest.post(url)
                .header("token", TOKEN)
                .fields(fields)
                .asJson();

**Environmental Data:**

Android API 33
Android Gradle JDK - Embedded JDK version 11.0.12

build.gradle has following:-

    compileSdkVersion 33
    buildToolsVersion "33.0.0"
    targetSdkVersion 33

   compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
Dependency :
implementation 'com.konghq:unirest-java-core:4.0.0-RC4'

**Additional context**

Android studio files display the following messages::-

Class file kong.unirest.core.java.JavaClientBuilder.java - Library source doesn't match the bytecode for class JavaClientbuilder.java
Class file for JavaClientBuilder.class - Decompiled .class file bytecode version:55.0(Java 11)
dalvik.system.BaseDexClassLoader.java - Decompiled .class file bytecode version:52.0(Java 8)

**Comment by ryber** [comment]
are you building this on Android? I'm guessing Google has not implemented the java Http Client

**Comment by sunithapremjee** [comment]
Yes, I am building on Android.
The project is using Android API 33 library, JDK, and Unirest library. Android studio default JDK (java 11) has java.net.http.HttpClient.Please see the picture attached.

![defaultJDK](https://user-images.githubusercontent.com/9869417/187264639-63e58c29-cff4-4c16-bd3b-b1a0106f5453.png)

**Comment by ryber** [comment]
I'm not a Android developer so I'm really not sure, unirest isn't doing anything special here, just a normal import of java.net.http.HttpClient. I don't know why the classloader would not be able to find it

**Comment by sunithapremjee** [comment]
Ok. I am just posting the details below, since stuck on this issue for some time.

As in picture below kong.unirest.core.java.JavaClientBuilder.java class Library source doesn't match the bytecode.
Decompiled JavaClientBuilder.class file bytecode version:55( Java 11)

I have set java version to Java 11 for latest Unirest requirement.

![JavaclientBuilder_Unirest_Class](https://user-images.githubusercontent.com/9869417/187297804-60169645-81dd-4ed5-9857-19c3f1be1020.png)

**Comment by sunithapremjee** [comment]
Is there any Unirest dependency that supports arm64 environments?

**Comment by ryber** [comment]
Unirest is just java, and Java supports ARM, Unirest itself is entirely agnostic towards CPUs

**Comment by ashishb** [comment]
> Android studio default JDK (java 11) has java.net.http.HttpClient.Please see the picture attached.

I don't think this is entirely true.
As far as I know, Google's Android SDK has full support for Java 8 and patchy support for APIs beyond that.
The full list of the supported Java 11 APIs on Android are listed at https://developer.android.com/studio/write/java11-default-support-table and it seems HttpClient is not in the list.

**Comment by sunithapremjee** [comment]
I already used Retrofit HTTP client, and everything worked out well. I will make sure to keep all the above information in mind.
Thanks, Ryan and Ashishb, for looking into the issue. By the way, I could find a Unirest repo
with Gradle dependency specifically for android(https://github.com/zeeshanejaz/unirest-android).
