### ISSUE TITLE
byte[] uploads

### ISSUE THREAD

**Issue by Jamesgt** [Kong/unirest-java#91]
It would be nice to have also

```
public MultipartBody field(String name, byte[] bytesOfFile) { ... }
```

Then not only files written to disk can be sent, but also ones generated and kept only in memory.

**Comment by varra4u** [comment]
It's very surprising to see this as missing in such a good API !!! 

Please add it as it would be like very handy for uploads!!

Thanks,
Krishna

**Comment by varra4u** [comment]
For time being, I've edited the source code of com.mashape.unirest.request.body.MultipartBody and achieved it by adding the below method: 

public MultipartBody field(String name, InputStream stream, ContentType contentType, String fileName)
	{
		return field(name, new InputStreamBody(stream, contentType, fileName), true, contentType.getMimeType());
	}

**Comment by Jamesgt** [comment]
Nice, you can help their work by creating a pull request with your changes.

**Comment by SGrondin** [comment]
Yes please submit a PR for this. Make sure to include some tests.

**Comment by varra4u** [comment]
I did pull request, can find the status at: https://github.com/Mashape/unirest-java/pull/93

**Comment by zdavep** [comment]
Seeing inconsistent behavior on this pull request.  The following works...

final HttpResponse<String> resp = Unirest.post(url).header("accept", "application/json").field("file", file).asString();

However, when I change the `file` type from File to InputStream:

final HttpResponse<String> resp = Unirest.post(url).header("accept", "application/json").field("file", is).asString();

The following exception occurs (from a Netty web-service):

tInputStream(Http.java:87)
	at peregrine.client.CoreClient.postInputStream(CoreClient.java:224)
	at peregrine.client.CoreClient.uploadDocument(CoreClient.java:480)
	at peregrine.client.JsonClient.uploadDocument(JsonClient.java:203)
	at peregrine.client.Peregrine.main(Peregrine.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sbt.Run.invokeMain(Run.scala:67)
	at sbt.Run.run0(Run.scala:61)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:51)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:55)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
	at sbt.Logger$$anon$4.apply(Logger.scala:85)
	at sbt.TrapExit$App.run(TrapExit.scala:248)
	at java.lang.Thread.run(Thread.java:745)

I doesn't seem that the "file" key is getting added to the request.
